import 'package:google_generative_ai/google_generative_ai.dart';
import 'api_config.dart';
import 'app_localizations.dart';

class AIChatService {
  static const String _apiKey = geminiApiKey; 
  
  static Future<String> getResponse(String prompt) async {
    final isEn = AppLocalizations.isEnglish;

    if (_apiKey == 'YOUR_GEMINI_API_KEY') {
      return isEn 
        ? "Please provide a valid Gemini API key. This bot is currently in demo mode.\n\nNOTE: This information is for general informational purposes, consult your doctor."
        : "Lütfen geçerli bir Gemini API anahtarı sağlayın. Bu bot şu an demo modundadır.\n\nNOT: Bu bilgiler genel bilgilendirme amaçlıdır, doktorunuza danışın.";
    }

    try {
      final model = GenerativeModel(model: 'gemini-2.5-flash', apiKey: _apiKey);
      
      final systemPrompt = isEn
        ? "You are a Myasthenia Gravis (MG) support assistant. Help users kindly but NEVER make a medical diagnosis. Always remind them to consult their doctors. ALWAYS include the source/link of any medical or health-related information you provide at the end of your answer (e.g., links from Mayo Clinic, NIH, MGFA, etc.). Question: $prompt. Reply in English."
        : "Sen bir Myastenia Gravis (MG) destek asistanısın. Kullanıcılara nazikçe yardımcı ol ama asla tıbbi teşhis koyma. Her zaman doktorlarına danışmalarını hatırlat. Verdiğin tıbbi veya sağlıkla ilgili her bilginin kaynağını/linkini MUTLAKA cevabının sonuna ekle (örneğin Mayo Clinic, NIH, MGFA vb. linkleri). Soru: $prompt. Türkçe cevap ver.";

      final content = [Content.text(systemPrompt)];
      final response = await model.generateContent(content);
      
      final notice = isEn
        ? "\n\n⚠️ NOTE: This information is for general informational purposes, is generated by AI, and definitely does not replace doctor's advice."
        : "\n\n⚠️ NOT: Bu bilgiler genel bilgilendirme amaçlıdır, yapay zeka tarafından oluşturulmuştur ve kesinlikle doktor tavsiyesi yerine geçmez.";

      return "${response.text}$notice";
    } catch (e) {
      return isEn
        ? "An error occurred: $e\n\nPlease try again later."
        : "Bir hata oluştu: $e\n\nLütfen daha sonra tekrar deneyin.";
    }
  }
}
